import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import './HomePage.css';

const HomePage = () => {
    const { user, userRole } = useAuth();

    return (
        <div className="homepage">
            {/* Hero Section */}
            <section className="hero">
                <div className="hero-background">
                    <div className="gradient-orb orb-1"></div>
                    <div className="gradient-orb orb-2"></div>
                    <div className="gradient-orb orb-3"></div>
                </div>

                <div className="container">
                    <div className="hero-content">
                        <h1 className="hero-title animate-fade-in">
                            Transform Your Learning Journey with{' '}
                            <span className="gradient-text">AI-Powered Education</span>
                        </h1>
                        <p className="hero-description animate-fade-in">
                            Experience personalized study roadmaps, seamless note management, and intelligent progress tracking.
                            Whether you're a teacher or student, StudyApp revolutionizes the way you learn and teach.
                        </p>
                        <div className="hero-actions animate-fade-in">
                            {user ? (
                                <>
                                    <Link
                                        to={userRole === 'teacher' ? '/teacher/dashboard' : '/student/dashboard'}
                                        className="btn btn-primary btn-lg"
                                    >
                                        {userRole === 'teacher' ? '👨‍🏫 Teacher Dashboard' : '🎓 Student Dashboard'}
                                    </Link>
                                    <Link to={userRole === 'student' ? '/student/roadmap' : '/teacher/upload'} className="btn btn-secondary btn-lg">
                                        {userRole === 'student' ? '🗺️ Study Roadmap' : '📤 Upload Notes'}
                                    </Link>
                                </>
                            ) : (
                                <>
                                    <Link to="/signup" className="btn btn-primary btn-lg">
                                        Get Started Free
                                    </Link>
                                    <Link to="/login" className="btn btn-secondary btn-lg">
                                        Sign In
                                    </Link>
                                </>
                            )}
                        </div>
                    </div>
                </div>
            </section>

            {/* Features Section */}
            <section className="features">
                <div className="container">
                    <h2 className="section-title text-center">Powerful Features for Modern Learning</h2>
                    <p className="section-description text-center">
                        Everything you need to succeed in your educational journey
                    </p>

                    <div className="features-grid">
                        <div className="feature-card card-glass">
                            <div className="feature-icon">🤖</div>
                            <h3>AI-Powered Roadmaps</h3>
                            <p>Get personalized learning paths generated by Gemini AI, tailored to your goals and skill level.</p>
                        </div>

                        <div className="feature-card card-glass">
                            <div className="feature-icon">📚</div>
                            <h3>Smart Note Management</h3>
                            <p>Upload, organize, and access study materials seamlessly. Teachers share, students learn.</p>
                        </div>

                        <div className="feature-card card-glass">
                            <div className="feature-icon">📊</div>
                            <h3>Progress Tracking</h3>
                            <p>Monitor your learning journey with detailed analytics and AI-generated insights.</p>
                        </div>

                        <div className="feature-card card-glass">
                            <div className="feature-icon">💡</div>
                            <h3>AI Study Assistant</h3>
                            <p>Get instant answers to your questions and personalized study recommendations.</p>
                        </div>

                        <div className="feature-card card-glass">
                            <div className="feature-icon">👥</div>
                            <h3>Role-Based Access</h3>
                            <p>Separate interfaces for teachers and students, optimized for their unique needs.</p>
                        </div>

                        <div className="feature-card card-glass">
                            <div className="feature-icon">🎯</div>
                            <h3>Goal Setting</h3>
                            <p>Set learning objectives and track your progress towards achieving them.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* How It Works Section */}
            <section className="how-it-works">
                <div className="container">
                    <h2 className="section-title text-center">How It Works</h2>

                    <div className="steps-container">
                        <div className="step">
                            <div className="step-number">1</div>
                            <h3>Sign Up</h3>
                            <p>Create your account and choose your role - Teacher or Student</p>
                        </div>

                        <div className="step-connector"></div>

                        <div className="step">
                            <div className="step-number">2</div>
                            <h3>Set Your Goals</h3>
                            <p>Select your learning topics and let AI generate your personalized roadmap</p>
                        </div>

                        <div className="step-connector"></div>

                        <div className="step">
                            <div className="step-number">3</div>
                            <h3>Learn & Track</h3>
                            <p>Access notes, follow your roadmap, and monitor your progress in real-time</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section className="cta">
                <div className="container">
                    <div className="cta-content card-glass">
                        <h2>Ready to Transform Your Learning?</h2>
                        <p>Join thousands of students and teachers already using StudyApp</p>
                        {!user && (
                            <Link to="/signup" className="btn btn-primary btn-lg">
                                Start Learning Today
                            </Link>
                        )}
                    </div>
                </div>
            </section>
        </div>
    );
};

export default HomePage;
